# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Cache@2
  inputs:
    key: 'gatsby-cache-folder-20201222'
    path: .cache
  displayName: Cache gatsby-cache-folder
- task: Cache@2
  inputs:
    key: 'gatsby-public-folder-20201222'
    path: public
  displayName: Cache gatsby-public-folder
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm install -g gatsby-cli
    gatsby build --no-uglify
  displayName: 'npm install and build'
- task: CopyFiles@2
  inputs:
    SourceFolder: 'public/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftps://waws-prod-bay-141.ftp.azurewebsites.windows.net'
    username: $dev-obagiecommerce
    password: pcQFTTSlFR9X6kEWgYZZihmv914cvKrFqhjKdhKDQii8H9hmCxxGhM2Ar9NQ
    rootDirectory: '$(build.artifactstagingdirectory)'
    filePatterns: '**'
    remoteDirectory: /site/wwwroot/storefront
    clean: true
    cleanContents: false
    preservePaths: true
    trustSSL: false