# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- script: |
    gatsby serve
  displayName: 'gatsby serve'

- script: |
    npm install gatsby-plugin-offline
  displayName: 'gatsby plugin offline'

- task: CopyFiles@2
  inputs:
    SourceFolder: 'public/'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
- task: FtpUpload@2
  inputs:
    credentialsOption: 'inputs'
    serverUrl: 'ftps://waws-prod-dm1-121.ftp.azurewebsites.windows.net'
    username: dev-obagi\$dev-obagi
    password: sLjsGJxjcCRrburkoYi40xpCPtQcRfhNsd0amnZtTNC10sPovrFz7eYBtsAo
    rootDirectory: '$(build.artifactstagingdirectory)'
    filePatterns: '**'
    remoteDirectory: /site/wwwroot/storefront
    clean: true
    cleanContents: false
    preservePaths: true
    trustSSL: false
